@BASE_URL=http://localhost:8080/api
@USERNAME={{$env USERNAME}}
@PASSWORD={{$env PASSWORD}}

GET http://localhost:8080/api/users

### 🔍 1. ทดสอบสมัครสมาชิก (ไม่ต้องใช้ token)
POST {{BASE_URL}}/auth/local/register
Content-Type: application/json

{
    "username": "{{USERNAME}}",
    "email": "test{{$timestamp}}@example.com",
    "password": "{{PASSWORD}}"
}


### 🔍 5. ทดสอบแก้ไขข้อมูลตัวเอง (PUT)
PUT {{BASE_URL}}/users/me
Content-Type: application/json

{
    "username": "update{{USERNAME}}",
    "email": "update{{$timestamp}}@example.com",
    "password": "{{PASSWORD}}"
} 



### 🔍 4. ทดสอบดูผู้ใช้ทั้งหมด (อาจต้องสิทธิ์ admin)
GET {{BASE_URL}}/users/me
