GET http://localhost:8080/api/users


POST http://localhost:8080/api/auth/local/register
Content-Type: application/json

{
 
    "username": "jirapinya2",
    "email": "jirapinya03srikaew@gmail.com",
    "password": "Jirapinya@2546"
   
   

}




