
services:
  db:
    image: postgres:latest
    container_name: my_db_jirapinya
    ports:
      - "65432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/db:/var/lib/postgresql/data

  app:
    image: prawee/strapi
    container_name: my_app_jirapinya
    ports: 
      - "8080:1337"
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: false

